// Created by Valorr19
// modules.cpp

#include <core/common.hpp>

#include <core/features.hpp>

#include <valve/classes/CSchemaSystem.h>
#include <valve/schemas/CBaseEntity.h>
#include <valve/schemas/CBasePlayerController.h>
#include <valve/schemas/CBasePlayerPawn.h>
#include <valve/schemas/CCollisionProperty.h>
#include <valve/schemas/CCSGameRules.h>
#include <valve/schemas/CEconEntity.h>
#include <valve/schemas/CGameSceneNode.h>
#include <valve/schemas/CGrenade.h>
#include <valve/schemas/CPlantedC4.h>
#include <valve/schemas/CWeapon.h>

#include <modules/utils/entities/entities.h>
#include <modules/utils/events/events.h>
#include <modules/utils/frame_data/frame_data.h>
#include <modules/utils/input/input.h>
#include <modules/utils/local/local.h>
#include <modules/utils/tracing/tracing.h>
#include <modules/utils/view/view.h>
#include <modules/rage/misc/seed/seedtrigger.h>
#include <modules/legit/aimbot/legit.h>
#include <modules/legit/aimbot/legit_input.h>
#include <modules/utils/bones/bones.h>
#include <modules/utils/bounds/bounds.h>
#include <modules/utils/hitboxes/hitboxes.h>
#include <modules/utils/icons/icons.h>
#include <modules/visuals/esp/materials/materials.h>
#include <modules/legit/movement/airstrafe.h>
#include <modules/legit/movement/bunnyhop.h>
#include <modules/legit/movement/fastladder.h>
#include <modules/legit/movement/slowwalk.h>
#include <modules/legit/movement/test_strafer.h>
#include <modules/rage/misc/antiaim/antiaim.h>
#include <modules/rage/misc/auto/autoshoot/autoshoot.h>
#include <modules/rage/misc/auto/autoscope/autoscope.h>
#include <modules/rage/misc/auto/autostop/autostop.h>
#include <modules/rage/misc/backtrack/backtrack.h>
#include <modules/rage/misc/extrapolation/extrapolation.h>
#include <modules/rage/misc/hitpointscale/hitpointscale.h>
#include <modules/rage/misc/mindamage/mindamage.h>
#include <modules/rage/misc/auto/autopeak/autopeak.h>
#include <modules/rage/misc/auto/duckpeek/duckpeek.h>
#include <modules/rage/misc/nospread/nospread.h>
#include <modules/rage/misc/penetration/penetration.h>
#include <modules/rage/misc/penetration/penetration_crosshair.h>
#include <modules/rage/misc/visualize/visualize.h>
#include <modules/rage/misc/prediction/prediction.h>
#include <modules/rage/misc/shared.h>
#include <modules/rage/silentaim/core.h>
#include <modules/visuals/esp/item/item.chams.h>
#include <modules/visuals/esp/item/item.glow.h>
#include <modules/visuals/esp/item/item.overlay.h>
#include <modules/visuals/esp/other/other.overlay.h>
#include <modules/visuals/esp/player/player.chams.h>
#include <modules/visuals/esp/player/player.glow.h>
#include <modules/visuals/esp/player/player.overlay.h>
#include <modules/visuals/esp/projectile/projectile.overlay.h>
#include <modules/visuals/esp/projectile/projectile.tracers.h>
#include <modules/visuals/misc/camera.h>
#include <modules/visuals/misc/dlight.h>
#include <modules/visuals/misc/hud.h>
#include <modules/visuals/misc/impacts.h>
#include <modules/visuals/misc/autobuy.h>
#include <modules/visuals/misc/clantag.h>
#include <modules/visuals/misc/killfeed.h>
#include <modules/visuals/misc/local_alpha.h>
#include <modules/visuals/misc/name_changer.h>
#include <modules/visuals/misc/onshot.h>
#include <modules/visuals/misc/projectile.trajectory.h>
#include <modules/visuals/misc/removals.h>
#include <modules/visuals/misc/reveal_radar.h>
#include <modules/visuals/misc/enemy_spec.h>
#include <modules/visuals/misc/scoreboard_weapons.h>
#include <modules/visuals/misc/server_lagger.h>
#include <modules/visuals/misc/viewmodel.h>
#include <modules/visuals/modelpreview/modelpreview.h>
#include <modules/visuals/skinchanger/agents.h>
#include <modules/visuals/skinchanger/econ_item_system.h>
#include <modules/visuals/skinchanger/gloves.h>
#include <modules/visuals/skinchanger/guns.h>
#include <modules/visuals/skinchanger/knives.h>
#include <modules/visuals/worldmodulation/exposure/exposure.h>
#include <modules/visuals/worldmodulation/sky/sky.h>
#include <modules/visuals/worldmodulation/lighting/lighting.h>
#include <modules/visuals/worldmodulation/world/world.h>
#include <modules/visuals/worldmodulation/fog/fog.h>
#include <modules/visuals/worldmodulation/worldblur/worldblur.h>
#include <modules/visuals/worldmodulation/bloom/bloom.h>
#include <modules/visuals/worldmodulation/gamma/gamma.h>
#include <modules/visuals/worldmodulation/wetness/wetness.h>
#include <modules/visuals/worldmodulation/smoke/smoke.h>
#include <modules/visuals/worldmodulation/weather/weather.h>
#include <modules/visuals/particles/manager.h>
#include <modules/visuals/particles/modulation.h>
#include <modules/visuals/particles/ground.h>
#include <modules/visuals/particles/hitkill.h>
#include <modules/visuals/particles/throwable_trail.h>
