#pragma once

namespace materials::vmat {
    inline const char* white_vmat = "<!-- kv3 encoding:text:version{e2187868-d75d-4585-8676-528310565846} format:generic:version{7412167c-739f-4116-9257-a61d67b33d4e} -->\n{\n\tShader = \"csgo_character.vfx\"\n}\n";
    inline const char* white_vmat_invis = "<!-- kv3 encoding:text:version{e2187868-d75d-4585-8676-528310565846} format:generic:version{7412167c-739f-4116-9257-a61d67b33d4e} -->\n{\n\tShader = \"csgo_character.vfx\"\n\tg_bIgnoreZ = true\n}\n";

    inline const char* latex_vmat = white_vmat;
    inline const char* latex_vmat_invis = white_vmat_invis;
    inline const char* glow_vmat = white_vmat;
    inline const char* glow_vmat_invis = white_vmat_invis;
    inline const char* ghost_vmat = white_vmat;
    inline const char* ghost_vmat_invis = white_vmat_invis;
    inline const char* flat_vmat = white_vmat;
    inline const char* flat_vmat_invis = white_vmat_invis;
    inline const char* bloom2_vmat = white_vmat;
    inline const char* bloom2_vmat_invis = white_vmat_invis;
    inline const char* glass_vmat = white_vmat;
    inline const char* glass_vmat_invis = white_vmat_invis;
    inline const char* generic_vmat = white_vmat;
    inline const char* generic_vmat_invis = white_vmat_invis;
    inline const char* unlit_vmat = white_vmat;
    inline const char* unlit_vmat_invis = white_vmat_invis;
    inline const char* solid_vmat = white_vmat;
    inline const char* solid_vmat_invis = white_vmat_invis;
    inline const char* wireframe_vmat = white_vmat;
    inline const char* wireframe_vmat_invis = white_vmat_invis;
    inline const char* bloom_vmat = white_vmat;
    inline const char* bloom_vmat_invis = white_vmat_invis;
    inline const char* illuminate_vmat = white_vmat;
    inline const char* illuminate_vmat_invis = white_vmat_invis;
    inline const char* gost_vmat = white_vmat;
    inline const char* gost_vmat_invis = white_vmat_invis;
    inline const char* crystal_vmat = white_vmat;
    inline const char* crystal_vmat_invis = white_vmat_invis;
    inline const char* gost2_vmat = white_vmat;
    inline const char* gost2_vmat_invis = white_vmat_invis;
    inline const char* metallic_vmat = white_vmat;
    inline const char* metallic_vmat_invis = white_vmat_invis;
    inline const char* flow_vmat = white_vmat;
    inline const char* flow_vmat_invis = white_vmat_invis;
    inline const char* darkmatter_vmat = white_vmat;
    inline const char* darkmatter_vmat_invis = white_vmat_invis;
    inline const char* data_vmat = white_vmat;
    inline const char* data_vmat_invis = white_vmat_invis;
    inline const char* chrome_vmat = white_vmat;
    inline const char* chrome_vmat_invis = white_vmat_invis;
    inline const char* plastic_vmat = white_vmat;
    inline const char* plastic_vmat_invis = white_vmat_invis;
    inline const char* energy_vmat = white_vmat;
    inline const char* energy_vmat_invis = white_vmat_invis;
    inline const char* hologram_vmat = white_vmat;
    inline const char* hologram_vmat_invis = white_vmat_invis;
    inline const char* galaxy_vmat = white_vmat;
    inline const char* galaxy_vmat_invis = white_vmat_invis;
    inline const char* gold_vmat = white_vmat;
    inline const char* gold_vmat_invis = white_vmat_invis;
    inline const char* neon_vmat = white_vmat;
    inline const char* neon_vmat_invis = white_vmat_invis;
    inline const char* xray_vmat = white_vmat;
    inline const char* xray_vmat_invis = white_vmat_invis;
    inline const char* liquid_vmat = white_vmat;
    inline const char* liquid_vmat_invis = white_vmat_invis;
    inline const char* pearl_vmat = white_vmat;
    inline const char* pearl_vmat_invis = white_vmat_invis;
    inline const char* distortion_vmat = white_vmat;
    inline const char* distortion_vmat_invis = white_vmat_invis;
    inline const char* outlines_vmat = white_vmat;
    inline const char* outlines_vmat_invis = white_vmat_invis;
}
